USE SaaDB
GO

DROP TABLE IF EXISTS [SAA_1H]

CREATE TABLE [SAA_1H](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [PAIKKA] [varchar](30) NOT NULL,
    [AIKA] [datetime] NOT NULL,
	[ILMANPAINE] [varchar](10),
	[SUHTEELLINEN_KOSTEUS] [varchar](10),
	[LAMPOTILA] [varchar](10),
	[LAMPOTILA_MAKSIMI] [varchar](10),
	[LAMPOTILA_MINIMI] [varchar](10),
	[TUULEN_SUUNTA] [varchar](10),
	[TUULEN_NOPEUS] [varchar](10),
	[TUULEN_NOPEUS_MAKSIMI] [varchar](10),
	[TUULEN_NOPEUS_MINIMI] [varchar](10)
 CONSTRAINT [SAA_1H_PK] PRIMARY KEY ([ID])
)

CREATE UNIQUE INDEX SAA_1H_PAIKKA_AIKA_UINDEX
   ON [SAA_1H] (PAIKKA, AIKA); 

GO

INSERT INTO [SAA_1H] (PAIKKA, AIKA)
SELECT DISTINCT
  PAIKKA,
  AIKA
FROM [SAA_RAAKA];

--Ilmanpaine
UPDATE [SAA_1H]   
SET ILMANPAINE = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'PA_PT1H_AV';

--Suhteellinen kosteus
UPDATE [SAA_1H]   
SET SUHTEELLINEN_KOSTEUS = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'RH_PT1H_AV';

--Ilman lämpötila
UPDATE [SAA_1H]   
SET LAMPOTILA = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'TA_PT1H_AV';

--Ilman lämpötila maksimi
UPDATE [SAA_1H]   
SET LAMPOTILA_MAKSIMI = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'TA_PT1H_MA';
	
--Ilman lämpötila minimi
UPDATE [SAA_1H]   
SET LAMPOTILA_MINIMI = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'TA_PT1H_MI';

--Tuulen suunta
UPDATE [SAA_1H]   
SET TUULEN_SUUNTA = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'WD_PT1H_AV';

--Tuulen nopeus
UPDATE [SAA_1H]   
SET TUULEN_NOPEUS = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'WS_PT1H_AV';

--Tuulen nopeus maksimi
UPDATE [SAA_1H]   
SET TUULEN_NOPEUS_MAKSIMI = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'WS_PT1H_MA';

--Tuulen nopeus minimi
UPDATE [SAA_1H]   
SET TUULEN_NOPEUS_MINIMI = [SAA_RAAKA].PARAMETRIN_ARVO
FROM [SAA_RAAKA]  
WHERE [SAA_RAAKA].AIKA = [SAA_1H].AIKA
	AND [SAA_RAAKA].PAIKKA = [SAA_1H].PAIKKA
	AND [SAA_RAAKA].PARAMETRIN_NIMI = 'WS_PT1H_MI';

GO