USE SaaDB
GO

DROP TABLE IF EXISTS [SAA_RAAKA]

CREATE TABLE [SAA_RAAKA](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [PAIKKA] [varchar](30) NOT NULL,
    [AIKA] [datetime] NOT NULL,
	[PARAMETRIN_NIMI] [varchar](10) NOT NULL,
	[PARAMETRIN_ARVO] [varchar](10)
 CONSTRAINT [SAA_RAAKA_PK] PRIMARY KEY ([ID])
)
GO

CREATE NONCLUSTERED INDEX SAA_RAAKA_PARAMETRIN_ARVO_NONC_INDEX
	ON [SAA_RAAKA] ([PARAMETRIN_NIMI]) INCLUDE ([PAIKKA],[AIKA],[PARAMETRIN_ARVO])