USE SaaDB
GO

DROP TABLE IF EXISTS [SAATIEDOT_XML]

----CREATE LOADING TABLE----
CREATE TABLE [SAATIEDOT_XML](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [XML] [xml] NOT NULL,
    [LATAUS_PAIVAMAARA] [datetime] NOT NULL,
    [KYSELY] [varchar](2000) NOT NULL,
 CONSTRAINT [SAA_XML_PK] PRIMARY KEY ([ID])
)

GO