USE SaaDB
GO

DROP TABLE IF EXISTS [SAATIEDOT_RAAKA]

CREATE TABLE [SAATIEDOT_RAAKA](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [PAIKKA] [varchar](50) NOT NULL,
    [AIKA] [datetime] NOT NULL,
	[PARAMETRIN_NIMI] [varchar](20) NOT NULL,
	[PARAMETRIN_ARVO] [varchar](20)
 CONSTRAINT [SAATIEDOT_RAAKA_PK] PRIMARY KEY ([ID])
)
GO

CREATE NONCLUSTERED INDEX SAA_RAAKA_PARAMETRIN_ARVO_NONC_INDEX
	ON [SAATIEDOT_RAAKA] ([PARAMETRIN_NIMI]) INCLUDE ([PAIKKA],[AIKA],[PARAMETRIN_ARVO])