USE SaaDB
GO

----IMPORT XML----
DECLARE @xmlData XML;
SET @xmlData = (
  SELECT * FROM OPENROWSET (
    BULK 'TIEDOSTO_POLKU\SAATIEDOT.XML', SINGLE_CLOB
  ) AS xmlData
);

INSERT INTO [SaaDB].[dbo].[SAA_XML](XML, LATAUS_PAIVAMAARA, KYSELY)
VALUES (@xmlData, SYSUTCDATETIME(), 'KYSELY')

GO
